version: 2.1

## ALIASES ##
tagged_builds: &tagged_builds
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/
prod_env: &prod_env
  env: prod
  context:
    - org_global
    - catalog_api_prod
stage_env: &stage_env
  env: stage
  context:
    - org_global
    - catalog_api_prod

## COMMANDS ##
commands:
  tf_init_plan:
    description: Initialize Terraform and plan with appropriate backend, vars, and mode
    parameters:
      env:
        type: string
        default: dev
      mode:
        type: string
    steps:
      - run:
          command: |      
            terraform init -input=false -backend-config="backends/<< parameters.env >>.s3.tfbackend"
            terraform << parameters.mode >> -out="tf-plan-out" \
            -var="env=<< parameters.env >>" \
            -var="aws_region=${AWS_REGION}" \
            -var="aws_account_id=${AWS_ACCOUNT_ID}" \
            -var="safe_ips=${SAFE_IPS}" \
            -var="domain_name=${DOMAIN_NAME}" \
            -var="default_image=animaldna/sleep:latest"

workflows:
  deploy_untagged:
    when:
      and:
        - equal: [master, << pipeline.git.branch >>]
    jobs:
      - init_and_plan:
          <<: *prod_env
          mode: plan
      - apply:
          <<: *prod_env
          requires:
            - init_and_plan
  deploy_tagged:
    jobs:
      - init_and_plan:
          name: stage_init_plan
          <<: *tagged_builds
          <<: *stage_env
          mode: plan
      - apply:
          name: stage_apply
          <<: *tagged_builds
          <<: *stage_env
          requires:
            - stage_init_plan
      - hold_for_stage_review:
          <<: *tagged_builds
          type: approval
          requires:
            - stage_apply
      - init_and_plan:
          name: prod_init_plan
          <<: *tagged_builds
          <<: *prod_env
          mode: plan
          requires:
            - hold_for_stage_review
      - hold_for_prod_review:
          <<: *tagged_builds
          type: approval
          requires:
            - prod_init_plan
      - apply:
          name: prod_apply
          <<: *tagged_builds
          <<: *prod_env
          requires:
            - hold_for_prod_review
      - destroy:
          name: destroy_stage
          <<: *tagged_builds
          <<: *stage_env
          mode: plan -destroy
          requires:
            - hold_for_prod_review
        
jobs:
  init_and_plan:
    parameters:
      env:
        type: string
        default: dev
      mode:
        type: string
    working_directory: /tmp/terraform-infra
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - tf_init_plan:
          env: << parameters.env >>
          mode: << parameters.mode >>
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    parameters:
      env:
        type: string
        default: dev
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve \
            -var="env=<< parameters.env >>" \
            -var="aws_region=${AWS_REGION}" \
            -var="aws_account_id=${AWS_ACCOUNT_ID}" \
            -var="safe_ips=${SAFE_IPS}" \
            -var="domain_name=${DOMAIN_NAME}" \
            -var="default_image=animaldna/sleep:latest"
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
    parameters:
      env:
        type: string
      mode:
        type: string
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - tf_init_plan:
          env: << parameters.env >>
          mode: << parameters.mode >>
      - run:
          name: destroy
          command: |
            terraform destroy -auto-approve \
            -var="env=<< parameters.env >>" \
            -var="aws_region=${AWS_REGION}" \
            -var="aws_account_id=${AWS_ACCOUNT_ID}" \
            -var="safe_ips=${SAFE_IPS}" \
            -var="domain_name=${DOMAIN_NAME}" \
            -var="default_image=animaldna/sleep:latest"