version: 2.1
production_only: &prod_only
  filters:
    branches:
      only: master

workflows:
  deploy_infrastructure:
    jobs:
      - init_and_plan:
          name: stage_init_plan
          env: stage
          context:
            - org_global
            - catalog_api_dev
      - apply:
          name: stage_apply
          env: stage
          context:
            - org_global
            - catalog_api_dev
      - hold_for_stage_review:
          <<: *prod_only
          type: approval
          requires:
            - stage_apply
      - init_and_plan:
          <<: *prod_only
          name: prod_init_plan
          env: prod
          context:
            - org_global
            - catalog_api_prod
          requires:
            - hold_for_stage_review
      - hold_for_prod_review:
          <<: *prod_only
          type: approval
          requires:
            - prod_init_plan
      - apply:
          <<: *prod_only
          name: prod_apply
          env: prod
          context:
            - org_global
            - catalog_api_prod
          requires:
            - hold_for_prod_review
        


jobs:
  init_and_plan:
    parameters:
      env:
        type: string
        default: dev
    working_directory: /tmp/terraform-infra
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false -backend-config="/backends/<< parameters.env >>.s3.tfbackend"
            terraform plan -out="tf-plan-out" \
            -var="env=<< parameters.env >>" \
            -var="aws_region=${AWS_REGION}" \
            -var="aws_account_id=${AWS_ACCOUNT_ID}" \
            -var="safe_ips=${SAFE_IPS}" \
            -var="domain_name=${DOMAIN_NAME}" \
            -var="project_name=${CIRCLE_PROJECT_REPONAME}"
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    parameters:
      env:
        type: string
        default: dev
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve \
            -var="env=<< parameters.env >>" \
            -var="aws_region=${AWS_REGION}" \
            -var="aws_account_id=${AWS_ACCOUNT_ID}" \
            -var="safe_ips=${SAFE_IPS}" \
            -var="domain_name=${DOMAIN_NAME}" \
            -var="project_name=${CIRCLE_PROJECT_REPONAME}"
      - persist_to_workspace:
          root: .
          paths:
            - .